import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import OpenAI from 'openai';

// Initialize AI client using OpenAI-compatible SDK (supports OpenRouter and Groq)
const getAiClient = () => {
  const apiKey = process.env.OPENROUTER_API_KEY || process.env.GROQ_API_KEY;
  const baseURL = process.env.OPENROUTER_API_KEY
    ? 'https://openrouter.ai/api/v1'
    : (process.env.AI_BASE_URL || 'https://api.groq.com/openai/v1');

  return new OpenAI({
    apiKey,
    baseURL,
  });
};

export async function POST(req: NextRequest) {
  const { userId } = await auth();
  if (!userId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const { messages } = await req.json();

    const sanitizedMessages = Array.isArray(messages) 
      ? messages.filter((m: any, i: number) => i > 0 || m.role === 'user') 
      : [];

    const ai = getAiClient();

    const response = await ai.chat.completions.create({
      model: 'qwen/qwen3.6-27b', 
      messages: [
        {
          role: 'system',
          content: `You are ECHO, a compassionate, articulate, and supportive AI mental health companion. Your role is to:
- Listen actively and empathetically to users
- Provide clear, comforting, and supportive responses without ambiguity
- Encourage healthy coping strategies, mindfulness, and practical self-care
- Gently suggest professional help when needed
- Never diagnose or prescribe medical treatments
- Keep responses warm, calm, grounded, and concise
- Keep your phrasing natural and conversational so it flows smoothly and soothingly
- Output ONLY your direct conversational message to the user. Do NOT include any internal thoughts, reasoning steps, preambles, or <think> tags.`,
        },
        ...sanitizedMessages,
      ],
      max_tokens: 800,
      temperature: 0.6,
      stream: false,
    });

    let responseText = response.choices[0]?.message?.content || '';

    // Strip out <think>...</think> reasoning blocks if generated by reasoning models
    responseText = responseText.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
    // Also remove unclosed <think> tag if any
    responseText = responseText.replace(/<think>[\s\S]*/gi, '').trim();

    return NextResponse.json({
      message: responseText || "I'm listening and I'm here for you. 💜",
    });

  } catch (error: any) {
    console.error('AI API Error:', error.message);
    return NextResponse.json({ 
      error: 'AI Companion is momentarily unavailable.',
      details: process.env.NODE_ENV === 'development' ? error.message : undefined 
    }, { status: 500 });
  }
}