import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import OpenAI from 'openai';

// Initialize AI client using OpenAI-compatible SDK (supports OpenRouter and Groq)
const getAiClient = () => {
  const apiKey = process.env.OPENROUTER_API_KEY || process.env.GROQ_API_KEY;
  const baseURL = process.env.OPENROUTER_API_KEY
    ? 'https://openrouter.ai/api/v1'
    : (process.env.AI_BASE_URL || 'https://api.groq.com/openai/v1');

  return new OpenAI({
    apiKey,
    baseURL,
  });
};

export async function POST(req: NextRequest) {
  const { userId } = await auth();
  if (!userId) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const { messages } = await req.json();

    const sanitizedMessages = Array.isArray(messages) 
      ? messages.filter((m: any, i: number) => i > 0 || m.role === 'user') 
      : [];

    const ai = getAiClient();

    const response = await ai.chat.completions.create({
      model: 'qwen/qwen3.8-27b', 
      messages: [
        {
          role: 'system',
          content: `You are ECHO, a warm, thoughtful, and articulate AI mental health companion.

GUIDELINES FOR YOUR RESPONSES:
1. Tone & Voice: Speak like a caring, supportive, and grounded human friend. Be empathetic, calm, and genuine. Avoid robotic clichés, preachy monologues, or forced textbook scripts (e.g., avoid repetitive intros like "Let's take a moment to just be...").
2. Clarity & Conciseness: Keep your replies clear, digestible, and focused (2 to 4 sentences or a couple of short paragraphs).
3. Formatting Rules:
   - STRICT: NEVER use asterisks (*) anywhere in your reply. Do NOT use * for bullet points, bolding, italics, or emphasis.
   - Write in clean, natural sentences with normal line breaks between thoughts or paragraphs.
   - If suggesting an exercise or steps, describe them conversationally or on clean new lines without asterisks.
4. Validation & Engagement: Acknowledge what the user is experiencing, provide gentle reassurance or a practical perspective, and ask an open, supportive question to keep the conversation going naturally.
5. Safety: Never diagnose, prescribe medications, or offer clinical treatment. Gently suggest reaching out to a professional or support hotline if in distress.
6. Clean Output: Output ONLY your direct conversational message. Never include internal monologue, thinking blocks, or meta-commentary.`,
        },
        ...sanitizedMessages,
      ],
      max_tokens: 800,
      temperature: 0.6,
      stream: false,
    });

    let responseText = response.choices[0]?.message?.content || '';

    // Strip out <think>...</think> reasoning blocks if generated by reasoning models
    responseText = responseText.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
    // Also remove unclosed <think> tag if any
    responseText = responseText.replace(/<think>[\s\S]*/gi, '').trim();

    // Clean up any inline or leading asterisks into clean line breaks or plain text
    responseText = responseText
      .replace(/\s*\*\s+/g, '\n\n')
      .replace(/\*+/g, '')
      .replace(/\n{3,}/g, '\n\n')
      .trim();

    return NextResponse.json({
      message: responseText || "I'm listening and I'm here for you. 💜",
    });

  } catch (error: any) {
    console.error('AI API Error:', error.message);
    return NextResponse.json({ 
      error: 'AI Companion is momentarily unavailable.',
      details: process.env.NODE_ENV === 'development' ? error.message : undefined 
    }, { status: 500 });
  }
}